# Generated by Django 3.0.6 on 2020-06-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя человека')),
                ('surmane', models.CharField(max_length=100, verbose_name='Фамилия человека')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('image_url', models.CharField(max_length=300, verbose_name='Ссылка на фото')),
            ],
        ),
    ]
